# Generated by Django 5.0.3 on 2024-03-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='module',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='module',
            name='lessons',
            field=models.ManyToManyField(to='modules.lesson'),
        ),
    ]
