# Generated by Django 5.0.3 on 2024-03-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_alter_module_options_lesson_lesson_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='joke',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
