# Generated by Django 5.0.3 on 2024-03-17 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_question_answer_lesson_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='module',
            name='lessons',
        ),
        migrations.RemoveField(
            model_name='question',
            name='lesson_id',
        ),
        migrations.RemoveField(
            model_name='section',
            name='lesson_id',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('I', 'Informational')], default='I', max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='sections',
            field=models.ManyToManyField(related_name='lessons', to='modules.section'),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('module', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='modules.module')),
                ('questions', models.ManyToManyField(related_name='quizzes', to='modules.question')),
            ],
        ),
    ]
