# Generated by Django 5.0.3 on 2024-03-17 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('modules', '0004_remove_lesson_questions_remove_module_lessons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_type',
        ),
    ]
