# Generated by Django 5.0.3 on 2024-03-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_remove_lesson_lesson_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='content',
        ),
        migrations.AddField(
            model_name='lesson',
            name='section_1',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='section_2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='section_3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='section_4',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='section_5',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
