# Generated by Django 5.0.3 on 2024-03-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_remove_lesson_content_lesson_section_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='section_1',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='section_2',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='section_3',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='section_4',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='section_5',
        ),
        migrations.AddField(
            model_name='lesson',
            name='section_1_content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='section_1_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='section_2_content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='section_2_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='section_3_content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='section_3_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='section_4_content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='section_4_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='section_5_content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='section_5_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
