# Generated by Django 5.0.3 on 2024-03-17 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_useranswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
