# Generated by Django 5.0.3 on 2024-03-13 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_remove_lesson_section_1_remove_lesson_section_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='section_1_content',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='section_1_name',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='section_2_content',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='section_2_name',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='section_3_content',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='section_3_name',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='section_4_content',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='section_4_name',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='section_5_content',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='section_5_name',
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('contents', models.TextField()),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='sections',
            field=models.ManyToManyField(to='modules.section'),
        ),
    ]
