# Generated by Django 5.0.3 on 2024-03-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0008_remove_lesson_section_1_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='sections',
            field=models.ManyToManyField(related_name='sections', to='modules.section'),
        ),
    ]
