# Generated by Django 5.0.3 on 2024-03-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0008_delete_useranswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.CharField(choices=[('Y', 'Correct'), ('N', 'Incorrect')], default='Incorrect', max_length=15),
        ),
    ]
