# Generated by Django 5.0.3 on 2024-03-18 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0010_quizanswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizAnswer',
        ),
    ]
