# Generated by Django 5.0.3 on 2024-03-21 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0013_remove_lesson_status'),
        ('profile_page', '0011_alter_profile_learner_type_alter_profile_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonstatus',
            name='quiz',
        ),
        migrations.CreateModel(
            name='QuizStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_page.profile')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.quiz')),
            ],
        ),
    ]
