# Generated by Django 5.0.3 on 2024-03-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('modules', '0014_remove_lessonstatus_quiz_quizstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizstatus',
            name='status',
            field=models.CharField(
                choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')],
                default='Not Started', max_length=20),
        ),
    ]
