# Generated by Django 5.0.3 on 2024-03-23 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('modules', '0016_lessonstatus_finished_at_quizstatus_finished_at_and_more'),
        ('profile_page', '0011_alter_profile_learner_type_alter_profile_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizUserAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField()),
                ('is_correct',
                 models.CharField(choices=[('Y', 'Correct'), ('N', 'Incorrect')], default='Incorrect', max_length=15)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.answer')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_page.profile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.quiz')),
            ],
        ),
    ]
