# Generated by Django 5.0.3 on 2024-03-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0017_quizuseranswers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizuseranswers',
            name='answer',
        ),
    ]
