# Generated by Django 5.0.3 on 2024-04-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0018_remove_quizuseranswers_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Single Choice', 'Single Choice'), ('Multiple Choice', 'Multiple Choice'), ('Open Text', 'Open Text')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
