# Generated by Django 5.0.3 on 2024-04-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0019_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty_level',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='easy', max_length=20),
        ),
    ]
