# Generated by Django 5.0.4 on 2024-04-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('modules', '0022_alter_answer_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='sections',
            field=models.ManyToManyField(null=True, related_name='lessons', to='modules.section'),
        ),
    ]
