# Generated by Django 5.0.4 on 2024-04-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0023_alter_lesson_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='sections',
            field=models.ManyToManyField(default=None, null=True, related_name='lessons', to='modules.section'),
        ),
    ]
