# Generated by Django 5.0.4 on 2024-05-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('modules', '0025_alter_lesson_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quiz',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
