# Generated by Django 5.0.4 on 2024-04-23 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('profile_page', '0035_profile_receive_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type',
                 models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=50)),
                ('description', models.TextField()),
                ('screenshot', models.ImageField(upload_to='feedback/screenshots')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_page.profile')),
            ],
        ),
    ]
