# Generated by Django 5.0.3 on 2024-03-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leeriapprentices',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
