# Generated by Django 5.0.3 on 2024-03-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0002_leeriapprentices_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leeriapprentices',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
