# Generated by Django 5.0.3 on 2024-03-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('profile_page', '0002_alter_profile_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic_url',
            field=models.URLField(blank=True),
        ),
    ]
