# Generated by Django 5.0.3 on 2024-03-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0012_profile_chosen_language_alter_profile_learner_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A rookie! (Beginner)', 'Beginner'), ('A smart cookie! (Skilled)', 'Skilled'), ('A very smart cookie! (Advanced)', 'Advanced')], default='An avid learner!', max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='learner_type',
        ),
        migrations.AddField(
            model_name='profile',
            name='learner_type',
            field=models.ManyToManyField(to='profile_page.learningpath'),
        ),
    ]
