# Generated by Django 5.0.3 on 2024-03-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0013_learningpath_remove_profile_learner_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='learner_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='chosen_language',
        ),
        migrations.DeleteModel(
            name='LearningPath',
        ),
        migrations.AddField(
            model_name='profile',
            name='learner_type',
            field=models.CharField(choices=[('A rookie! (Beginner)', 'Beginner'), ('A smart cookie! (Skilled)', 'Skilled'), ('A very smart cookie! (Advanced)', 'Advanced')], default='An avid learner!', max_length=50),
        ),
    ]
