# Generated by Django 5.0.3 on 2024-03-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('profile_page', '0014_remove_profile_learner_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chosen_lamguage',
            field=models.CharField(choices=[('English', 'English'), ('German', 'German'), ('Spanish', 'Spanish')],
                                   default=7, max_length=30),
            preserve_default=False,
        ),
    ]
