# Generated by Django 5.0.3 on 2024-03-27 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0016_alter_profile_chosen_lamguage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='chosen_lamguage',
            new_name='chosen_language',
        ),
    ]
