# Generated by Django 5.0.3 on 2024-03-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0017_rename_chosen_lamguage_profile_chosen_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='learner_type',
            field=models.CharField(choices=[('A rookie! (Beginner)', 'Beginner'), ('A pookie! (Skilled)', 'Skilled'), ('A smart cookie! (Advanced)', 'Advanced')], default='An avid learner!', max_length=50),
        ),
    ]
