# Generated by Django 5.0.3 on 2024-03-27 10:42

import profile_page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0018_alter_profile_learner_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic_url',
            field=models.ImageField(default=profile_page.models.get_random_profile_pic, upload_to='uploads/'),
        ),
    ]
