# Generated by Django 5.0.3 on 2024-03-28 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('modules', '0018_remove_quizuseranswers_answer'),
        ('profile_page', '0019_alter_profile_profile_pic_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='chosen_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.language'),
        ),
    ]
