# Generated by Django 5.0.3 on 2024-03-29 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0020_alter_profile_chosen_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='chosen_language',
        ),
    ]
