# Generated by Django 5.0.3 on 2024-03-30 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('modules', '0018_remove_quizuseranswers_answer'),
        ('profile_page', '0023_alter_profile_profile_pic_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chosen_language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='modules.language'),
            preserve_default=False,
        ),
    ]
