# Generated by Django 5.0.3 on 2024-03-30 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0025_learnertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='learner_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_page.learnertype'),
        ),
    ]
