# Generated by Django 5.0.3 on 2024-04-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('profile_page', '0028_alter_profile_chosen_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='receive_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
