# Generated by Django 5.0.3 on 2024-04-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('profile_page', '0029_profile_receive_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='receive_notifications',
            field=models.CharField(choices=[('Send', 'Send'), ('Do not send', 'Do not send')], default='Send',
                                   max_length=50),
        ),
    ]
