# Generated by Django 5.0.4 on 2024-04-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0031_notificationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsettings',
            name='discussion_notifications',
            field=models.CharField(choices=[('Send', 'Send'), ('Do not send', 'Do not send')], default='Send', max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='new_modules_notifications',
            field=models.CharField(choices=[('Send', 'Send'), ('Do not send', 'Do not send')], default='Send', max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='new_resources_notifications',
            field=models.CharField(choices=[('Send', 'Send'), ('Do not send', 'Do not send')], default='Send', max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='quiz_results_notifications',
            field=models.CharField(choices=[('Send', 'Send'), ('Do not send', 'Do not send')], default='Send', max_length=50),
        ),
    ]
