# Generated by Django 5.0.4 on 2024-04-19 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('profile_page', '0033_profile_discussion_notifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='receive_notifications',
        ),
    ]
