# Generated by Django 5.0.4 on 2024-04-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('profile_page', '0034_remove_profile_receive_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='receive_notifications',
            field=models.CharField(choices=[('Send', 'Send'), ('Do not send', 'Do not send')], default='Send',
                                   max_length=50),
        ),
    ]
