# Generated by Django 5.0.3 on 2024-03-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('discussion_forums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
