# Generated by Django 5.0.4 on 2024-04-11 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('discussion_forums', '0004_remove_comment_post_comment_topic_delete_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentDeletionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deletion_time', models.DateTimeField(auto_now_add=True)),
                ('comment',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion_forums.comment')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                 to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
