# Generated by Django 5.0.4 on 2024-04-12 08:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('discussion_forums', '0006_alter_comment_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='starter',
        ),
    ]
