# Generated by Django 5.0.4 on 2024-04-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('resource_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
