# Generated by Django 5.0.4 on 2024-04-16 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('modules', '0022_alter_answer_is_correct'),
        ('resource_library', '0003_resource_related_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='related_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_lesson',
                                    to='modules.lesson'),
        ),
    ]
