# Generated by Django 5.0.4 on 2024-04-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('resource_library', '0004_alter_resource_related_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(default='Description is flying to us...'),
        ),
    ]
